package com.uustock.aitrader.droolsbroker 
rule "Using a global"
when
then
	System.out.println("hello");
end
rule "Too Hot"
   dialect "mvel"
   when
      temp : Temperature( value > 85 )
   then
      System.out.println(
         " F is too hot."
        + " Declare HEAT WARNING!"); 
end

rule "Too Cold"
   dialect "mvel"
   when
      temp : Temperature( value < 32 )
   then
      System.out.println(
          " F is too cold."
         + " Declare FREEZE WARNING!"); 
end
